// Sync Worker: POST /api/sync merges pushed cards into D1 and returns every
// card changed since the client's cursor. Merge semantics live in the same
// extension/lib/merge.js the clients run (wrangler bundles it in), so server
// and clients always agree.
//
// Auth is a bearer capability token generated by the extension; the server
// stores only its SHA-256 and self-provisions a user on first sight — no
// accounts. Static assets under ../pwa are served by the assets handler for
// every non-/api path.

import { cardKey, mergeCards } from '../../extension/lib/merge.js';

const MAX_BODY_BYTES = 5 * 1024 * 1024;
const MAX_CARDS_PER_USER = 6000;
const MAX_DOC_BYTES = 4096; // sentence cards carry a full sentence + defs
const CLOCK_SLACK_MS = 5 * 60 * 1000;
const TOMBSTONE_TTL_MS = 90 * 24 * 60 * 60 * 1000;
const NEW_USERS_PER_IP_PER_HOUR = 10;
const SQL_CHUNK = 50; // stay well under D1's bound-parameter limit

// /api/news: read current news on the topics the learner is studying and write
// them an original Mandarin passage pitched just above their level. The search
// is either the model's own web tool (OpenAI/Azure) or Google News RSS gathered
// here (fal) — see providerConfigured. It's expensive, so the Worker caches one
// digest per user in D1 and won't call the model more than once per
// NEWS_MIN_INTERVAL — a burst of clicks or new-tab opens cannot run up the bill.
const NEWS_TTL_MS = 12 * 60 * 60 * 1000;
const NEWS_MIN_INTERVAL_MS = 60 * 1000; // anti-spam floor on same-difficulty regeneration
const MAX_PROFILE_BYTES = 20 * 1024;
const MAX_SOURCES = 8;
const MAX_ARTICLE_CHARS = 8000;
// The digest runs on fal.ai (fal-ai/any-llm proxies GPT/Claude/Gemini/Llama —
// pick with the FAL_MODEL var). fal has no web-search tool, so the Worker does
// the searching itself: fal infers topics -> Google News RSS (keyless) fetches
// current headlines -> fal writes the passage from them.
const FAL_URL = 'https://fal.run/fal-ai/any-llm';
const DEFAULT_FAL_MODEL = 'google/gemini-flash-1.5';
const MAX_TOPICS = 4;
const MAX_QUERIES = 5;
const MAX_NEWS_ITEMS = 24;
const NEWS_PER_QUERY = 6;

// /api/ask: the tutor beside the HSK study guides. One short question at a
// time about the guide the learner is reading, optionally pointing at a
// passage they highlighted. Cheap per call, but a chat invites many calls, so
// it is capped per user per hour.
const ASK_PER_HOUR = 40;

// /api/placement: one turn of the adaptive placement interview — mark the
// answer the learner just typed, then set the next task at the level the
// client asked for. The client owns the ladder (extension/lib/placement.js);
// this endpoint is stateless and never decides when the interview ends, so a
// run's length and cost are known in advance. Capped per user per hour in
// turns, since one interview is a dozen or so calls.
const PLACEMENT_PER_HOUR = 60;

// /api/translate: an English back for a card whose Chinese is not in the
// dictionary or the example corpus — a sentence highlighted in an article, or
// one the tutor just wrote. Without it such a card falls back to a word-by-word
// gloss, which tells you what the words are but not what the sentence says.
// One short call, so the cap is generous compared to the tutor's.
const TRANSLATE_PER_HOUR = 200;
const MAX_TRANSLATE_CHARS = 200;
const MAX_TRANSLATION_CHARS = 400;
const USAGE_LOG_TTL_MS = 24 * 60 * 60 * 1000;
const MAX_QUESTION_CHARS = 800;
const MAX_SELECTION_CHARS = 1200;
const MAX_CONTEXT_CHARS = 4000;
const MAX_HISTORY_TURNS = 10;
const MAX_HISTORY_CHARS = 1500;
const MAX_ANSWER_CHARS = 4000;

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'authorization, content-type, x-provider-key',
  'Access-Control-Max-Age': '86400',
};

function json(body, status = 200) {
  return Response.json(body, { status, headers: CORS_HEADERS });
}

async function sha256Hex(text) {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

// Client clocks feed last-write-wins; clamp anything from the future so one
// device with a wrong clock cannot make its writes unbeatable. `srs.due` is a
// schedule, not a clock, and is legitimately in the future — left alone.
function clampClocks(doc, now) {
  const cap = now + CLOCK_SLACK_MS;
  const clamp = (v) => (typeof v === 'number' && v > cap ? cap : v);
  doc.savedAt = clamp(doc.savedAt);
  doc.lastSavedAt = clamp(doc.lastSavedAt);
  doc.deletedAt = clamp(doc.deletedAt);
  if (doc.srs) {
    doc.srs.reviewedAt = clamp(doc.srs.reviewedAt);
    // Drives the daily new-card allowance, so a future stamp would silently
    // eat tomorrow's introductions too.
    doc.srs.introducedAt = clamp(doc.srs.introducedAt);
  }
  return doc;
}

function validCard(doc) {
  if (!doc || typeof doc !== 'object' || Array.isArray(doc)) return false;
  if (typeof doc.simp !== 'string' || !doc.simp || doc.simp.length > 300) return false;
  if (typeof doc.pinyin !== 'string' || doc.pinyin.length > 600) return false;
  return JSON.stringify(doc).length <= MAX_DOC_BYTES;
}

async function getUser(db, tokenHash, ip, now) {
  const user = await db
    .prepare('SELECT id, version FROM users WHERE token_hash = ?')
    .bind(tokenHash)
    .first();
  if (user) return user;
  const { recent } = await db
    .prepare('SELECT COUNT(*) AS recent FROM users WHERE created_ip = ? AND created_at > ?')
    .bind(ip, now - 60 * 60 * 1000)
    .first();
  if (recent >= NEW_USERS_PER_IP_PER_HOUR) return null;
  await db
    .prepare('INSERT INTO users (token_hash, version, created_at, last_seen_at, created_ip) VALUES (?, 0, ?, ?, ?)')
    .bind(tokenHash, now, now, ip)
    .run();
  return db.prepare('SELECT id, version FROM users WHERE token_hash = ?').bind(tokenHash).first();
}

async function selectExisting(db, userId, keys) {
  const found = new Map();
  for (let i = 0; i < keys.length; i += SQL_CHUNK) {
    const chunk = keys.slice(i, i + SQL_CHUNK);
    const placeholders = chunk.map(() => '?').join(',');
    const { results } = await db
      .prepare(`SELECT card_key, doc FROM cards WHERE user_id = ? AND card_key IN (${placeholders})`)
      .bind(userId, ...chunk)
      .all();
    for (const row of results) found.set(row.card_key, JSON.parse(row.doc));
  }
  return found;
}

// Write the merged docs and bump the user's version cursor atomically. The
// UPDATE only succeeds if users.version is still what we read; every upsert
// is guarded on the same random txn nonce, so if another sync interleaved the
// whole batch no-ops and the caller retries against fresh state.
async function writeGuarded(db, user, merged, now) {
  const nonce = crypto.randomUUID();
  const newVersion = user.version + 1;
  const statements = [
    db.prepare('UPDATE users SET version = ?, txn = ?, last_seen_at = ? WHERE id = ? AND version = ?')
      .bind(newVersion, nonce, now, user.id, user.version),
  ];
  for (const [key, doc] of merged) {
    statements.push(
      db.prepare(
        `INSERT INTO cards (user_id, card_key, doc, version, deleted, deleted_at)
         SELECT ?1, ?2, ?3, ?4, ?5, ?6
         WHERE EXISTS (SELECT 1 FROM users WHERE id = ?1 AND txn = ?7)
         ON CONFLICT(user_id, card_key) DO UPDATE SET
           doc = excluded.doc, version = excluded.version,
           deleted = excluded.deleted, deleted_at = excluded.deleted_at`,
      ).bind(
        user.id, key, JSON.stringify(doc), newVersion,
        doc.deleted ? 1 : 0, doc.deleted ? doc.deletedAt || now : null, nonce,
      ),
    );
  }
  const results = await db.batch(statements);
  return results[0].meta.changes === 1 ? newVersion : null;
}

async function handleSync(request, env) {
  const auth = request.headers.get('authorization') || '';
  const token = auth.startsWith('Bearer ') ? auth.slice(7).trim() : '';
  if (!/^[A-Za-z0-9_-]{16,128}$/.test(token)) {
    return json({ error: 'missing or malformed bearer token' }, 401);
  }

  const length = Number(request.headers.get('content-length') || 0);
  if (length > MAX_BODY_BYTES) return json({ error: 'body too large' }, 413);
  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: 'invalid JSON' }, 400);
  }
  const since = Number.isInteger(body.since) && body.since >= 0 ? body.since : 0;
  const incoming = Array.isArray(body.cards) ? body.cards : [];
  if (incoming.length > MAX_CARDS_PER_USER) return json({ error: 'too many cards' }, 413);

  const now = Date.now();
  const db = env.DB;
  const ip = request.headers.get('cf-connecting-ip') || 'unknown';
  const user = await getUser(db, await sha256Hex(token), ip, now);
  if (!user) return json({ error: 'too many new pairings from this address; try later' }, 429);

  const docs = new Map(); // card_key -> validated incoming doc
  for (const raw of incoming) {
    if (!validCard(raw)) return json({ error: 'invalid card in payload' }, 400);
    const doc = clampClocks(raw, now);
    const key = cardKey(doc);
    docs.set(key, mergeCards(docs.get(key), doc));
  }

  let version = user.version;
  if (docs.size > 0) {
    // Optimistic-concurrency loop: read current rows, merge, guarded write;
    // if another sync for the same user landed in between, retry on the
    // fresh rows. Merging is idempotent so retries are safe.
    let attempt = 0;
    for (;;) {
      const existing = await selectExisting(db, user.id, [...docs.keys()]);
      if (attempt === 0) {
        // Quota counts only keys the server has never seen — a full re-push
        // of an existing deck (e.g. after token rotation) stays legal.
        const { total } = await db
          .prepare('SELECT COUNT(*) AS total FROM cards WHERE user_id = ?')
          .bind(user.id)
          .first();
        const fresh = [...docs.keys()].filter((k) => !existing.has(k)).length;
        if (total + fresh > MAX_CARDS_PER_USER) {
          return json({ error: 'card limit exceeded' }, 413);
        }
      }
      const merged = new Map();
      for (const [key, doc] of docs) {
        merged.set(key, mergeCards(existing.get(key), doc));
      }
      const written = await writeGuarded(db, user, merged, now);
      if (written !== null) {
        version = written;
        break;
      }
      if (++attempt >= 4) return json({ error: 'conflict, retry later' }, 409);
      const fresh = await db
        .prepare('SELECT id, version FROM users WHERE id = ?')
        .bind(user.id)
        .first();
      user.version = fresh.version;
    }
  } else {
    await db
      .prepare('UPDATE users SET last_seen_at = ? WHERE id = ?')
      .bind(now, user.id)
      .run();
  }

  const { results } = await db
    .prepare('SELECT doc FROM cards WHERE user_id = ? AND version > ?')
    .bind(user.id, since)
    .all();
  return json({ version, cards: results.map((r) => JSON.parse(r.doc)) });
}

// ---------------------------------------------------------------------------
// AI news digest: read current news on the learner's topics, synthesize a
// stretch-level Mandarin passage.
// ---------------------------------------------------------------------------

const OUTPUT_SHAPE = `Respond with ONLY a JSON object (no markdown fences, no text before or after):
{
  "level": "one-sentence level estimate",
  "topics": ["topic", "..."],
  "title": "Chinese title",
  "titlePinyin": "pinyin of the title",
  "article": "the passage in Simplified Chinese; separate paragraphs with \\n\\n",
  "englishSummary": "2-4 sentence English summary so the learner can check comprehension",
  "glossary": [ {"word": "Chinese word", "pinyin": "pinyin", "meaning": "concise English"} ],
  "sources": [ {"title": "real article title", "url": "https://..."} ]
}`;

// Step 1 (all providers): plan the news search from the learner's vocabulary.
const TOPICS_SYSTEM = `You analyze a Mandarin learner's flashcard profile and plan a personalized news search.

From the words they have saved and the words they keep failing, infer the themes they care about, and produce web-search queries to find CURRENT news on those themes. Also estimate their reading level as an HSK band (1 = beginner, 6 = advanced).

Estimate CONSERVATIVELY: a deck of a few hundred everyday words is usually HSK 1-2, not higher. When unsure, round DOWN — it is better to underestimate than to overwhelm the learner.

Respond with ONLY a JSON object (no markdown fences):
{
  "hsk": <integer 1-6, your single best estimate>,
  "level": "one-sentence explanation of the estimate",
  "topics": ["short topic label", "..."],
  "queries": ["中文新闻搜索词", "..."]
}
Give 2-4 topics and 3-5 concise queries. Prefer Chinese-language queries so the results are Chinese news.`;

// Step 2 (all providers): write the passage from headlines the Worker fetched.
// News vocabulary is intrinsically hard, so calibration is the whole game —
// the instructions below bias strongly toward "comprehensible", and the caller
// passes an explicit TARGET HSK band (see fetchNews) in the user message.
const NEWS_SYNTH_SYSTEM = `You write a SHORT, easy-to-read Mandarin Chinese news passage for ONE learner, carefully calibrated to their level.

You are given the learner's flashcard profile, a TARGET HSK band, and a list of REAL, CURRENT news headlines/snippets (gathered moments ago) with their sources.

Write ONE original short news digest in Simplified Chinese that tells the learner what is currently happening, drawn from the headlines. Write your own sentences; do not copy headline wording. Ground it ONLY in the provided headlines/snippets — never invent events, names, numbers, or quotes; if a snippet is thin, keep that point general.

CALIBRATION IS THE MOST IMPORTANT REQUIREMENT. News is naturally full of hard, formal vocabulary, so you must actively simplify:
- Write so a learner at the TARGET HSK band can read comfortably. Use mostly high-frequency words at or below that band.
- Explain the news in PLAIN, everyday language. Do NOT reuse official, technical, financial, or journalistic phrasing (政策术语、书面官话、专业名词). If an event involves an advanced concept, describe it in simple words or leave it out.
- Include only a FEW genuinely new "stretch" words — about 5-8 — and define EVERY one of them in the glossary.
- Keep sentences short and direct. At HSK 1-3, aim for roughly 8-14 characters per sentence and avoid stacked connectives (不仅…而且、虽然…但是…却). At HSK 4+, sentences may be longer.
- When in doubt, make it EASIER. It is much better to be slightly too easy than too hard.

Length by TARGET band: HSK 1-2 → about 80-150 Chinese characters; HSK 3-4 → 150-250; HSK 5-6 → 250-400. Keep to 3-5 short paragraphs.

WRITE NATURAL CHINESE. THIS IS THE MOST IMPORTANT RULE AND IT OUTRANKS EVERYTHING BELOW, INCLUDING THE VOCABULARY INSTRUCTIONS.

The failure this prompt exists to prevent is 翻译腔 — Chinese that is really English wearing Chinese characters. A native speaker reading a passage from you said "this reads like English translated Chinese" and pointed at 美丽的自然故事 ("beautiful nature story"): every character is a real word, the grammar parses, and no Chinese person would ever write it. That is the bar. Simple is not the same as wrong, and a learner who reads unnatural Chinese learns unnatural Chinese.

Your register model is a 小学 or 初中 语文 textbook passage, or a children's news bulletin (少儿新闻) — writing that is genuinely simple AND genuinely native. It is not "news Chinese with the hard words removed", and it is not English prose translated downward. Natural and easy are not opposites; advanced vocabulary is not what makes writing sound Chinese.

- NEVER build English-shaped noun phrases. Chinese leans on VERBS where English piles up nouns and adjectives. Say 大自然很美 or 关于大自然的故事, not 美丽的自然故事. Say 这里的空气很干净, not 干净的空气质量.
- Stack at most one modifier before a noun. If you have written ADJ + 的 + ADJ + 的 + NOUN, or a whole clause + 的 + abstract noun, the sentence is English. Break it into two short Chinese sentences.
- Use real collocations, the ones a speaker has heard: 看电视 not 见电视, 下雨 not 落雨水, 提高水平 not 做高水平, 取得成绩 not 得到成绩.
- Correct, idiomatic measure words (一场比赛, 一条新闻, 一位专家, 一项研究) and correct 的/得/地.
- Aspect and time the Chinese way: 了 for completion or change of state, 过 for experience, 在/正在 for ongoing; time and place words BEFORE the verb (他昨天去了北京, never 他去北京昨天).
- Use topic-comment order, which is how Chinese actually organises a sentence: 这件事我知道 / 那个地方人很多. Reach for 把 and 被 only where a native writer would.
- Drop pronouns and connectives that Chinese leaves out. English needs a subject in every clause; Chinese does not. 因为…所以… and 虽然…但是… do not belong in every paragraph.
- Vary how sentences start. Real writing does not open six sentences in a row with 这个 or 我们.
- Chinese punctuation only: ，。、；：？！ and 《》 for titles. Never a Latin comma or period inside Chinese text.
- No pinyin, no English, no romanisation inside the passage.
- Headlines are short verb phrases the way Chinese headlines actually are (科学家发现新的海洋动物), not English-style noun phrases (关于海洋动物的美丽发现).

BEFORE YOU ANSWER, REREAD EVERY SENTENCE AND ASK: would a Chinese person say it this way, or does it sound translated? Rewrite every sentence that fails, even if that means dropping one of the learner's vocabulary words. A passage that is slightly off-topic or slightly short but sounds genuinely Chinese is a success; one that hits every target word and reads like a translation is a failure.

BUILD THE PASSAGE FROM THE LEARNER'S OWN VOCABULARY (listed in the message) — a primary goal, after staying at the target level and writing natural Chinese:
- Words IN THEIR REVIEW QUEUE RIGHT NOW come first. These are the cards they are actively drilling, and meeting one in a real sentence is worth more than any other word in the passage. Work in as many as read naturally — aim for a good handful — but never at the cost of a sentence a native speaker would not write.
- Reuse the learner's KNOWN words liberally; the passage should feel assembled from words they recognize.
- Work in some of their RECENTLY SAVED words too, used naturally so they see them in real context.
- Include a few of their STRUGGLING words, in short, clear, unambiguous sentences that model correct usage.
- Do NOT list the vocabulary or teach it explicitly, and do NOT force a word in — just use it naturally in the news writing.

${OUTPUT_SHAPE}`;

function bearerToken(request) {
  const auth = request.headers.get('authorization') || '';
  const token = auth.startsWith('Bearer ') ? auth.slice(7).trim() : '';
  return /^[A-Za-z0-9_-]{16,128}$/.test(token) ? token : null;
}

// Which model provider is configured. All three are used the same way — plain
// text in, text out — because grounding is done in the Worker (Google News
// RSS), not by the model. We tried OpenAI's built-in web_search tool and it
// ignored the instruction and fabricated source URLs, so the Worker owns the
// search for every provider. See fetchNews.
function providerConfigured(env) {
  if (env.OPENAI_API_KEY) return 'openai';
  if (env.AZURE_OPENAI_KEY && env.AZURE_OPENAI_ENDPOINT && env.AZURE_OPENAI_DEPLOYMENT) return 'azure';
  if (env.FAL_KEY) return 'fal';
  return null;
}

// Which credentials this request's model calls should run on — or a Response
// saying what the caller has to do about it. One codebase, two deployments:
//
//   Shared Worker (REQUIRE_USER_KEY = "true", how this repo deploys) — anyone
//   may pair with it, so every AI request must carry the caller's own provider
//   key in `x-provider-key`. It is used for that one request and never stored,
//   never logged, and never mixed with the Worker's own secrets; nobody's
//   model usage lands on the owner's bill.
//
//   Private Worker — leave REQUIRE_USER_KEY unset and put OPENAI_API_KEY (or
//   the Azure / fal equivalents) in `wrangler secret`. Every paired device
//   then gets the AI features with no key of its own. A caller-supplied key
//   still wins, so one deployment can serve both.
//
// Usage:  const model = resolveModel(request, env, 'the news digest');
//         if (model.error) return model.error;
//         ... callModel(model.env, ...)
function resolveModel(request, env, what) {
  const key = (request.headers.get('x-provider-key') || '').trim();
  if (key) {
    // A caller key replaces the whole provider block rather than merging into
    // it: a half-populated Azure group must not let one request authenticate
    // as itself and bill the owner.
    const only = (provider) => ({
      env: {
        ...env,
        OPENAI_API_KEY: '',
        AZURE_OPENAI_KEY: '',
        AZURE_OPENAI_ENDPOINT: '',
        AZURE_OPENAI_DEPLOYMENT: '',
        FAL_KEY: '',
        ...provider,
      },
    });
    if (/^sk-[A-Za-z0-9_-]{16,256}$/.test(key)) return only({ OPENAI_API_KEY: key });
    if (/^[0-9a-f-]{8,64}:[0-9a-f]{16,64}$/i.test(key)) return only({ FAL_KEY: key });
    return {
      error: json({
        error: 'that key was not recognized — paste an OpenAI key (starts with "sk-") '
          + 'or a fal.ai key ("<uuid>:<hex>") in the extension\'s Options page',
      }, 400),
    };
  }
  if (String(env.REQUIRE_USER_KEY) === 'true') {
    return {
      error: json({
        error: `${what} runs on your own AI key. Open the extension's Options page, `
          + 'paste an OpenAI API key under "AI features", and try again — the key is '
          + 'sent with your request and never stored on the server.',
      }, 503),
    };
  }
  if (!providerConfigured(env)) {
    return {
      error: json({
        error: `${what} is not configured on this server (set an OpenAI, Azure OpenAI, `
          + 'or fal.ai key, or paste your own key in the extension\'s Options page - see README)',
      }, 503),
    };
  }
  return { env };
}

// Turn a system + user prompt into text on whichever provider is configured.
// `images` (optional) are [{ mime, data }] the learner attached to the question.
async function callModel(env, system, prompt, images = []) {
  const provider = providerConfigured(env);
  // fal-ai/any-llm takes a string prompt and nothing else, so an attachment
  // cannot be sent there. Saying so in the prompt is better than answering as
  // if the picture were not there: the model can tell the learner.
  if (provider === 'fal') {
    const note = images.length
      ? `${prompt}\n\n(The learner attached ${images.length === 1 ? 'an image' : `${images.length} images`}, `
        + 'but this server is configured with a model that cannot see images. Say so briefly.)'
      : prompt;
    return callFal(env, system, note);
  }
  if (provider === 'azure') {
    const base = env.AZURE_OPENAI_ENDPOINT.replace(/\/+$/, '');
    const version = env.AZURE_OPENAI_API_VERSION || 'preview';
    return callOpenAIText({
      label: 'azure-openai',
      url: `${base}/openai/v1/responses?api-version=${version}`,
      headers: { 'api-key': env.AZURE_OPENAI_KEY },
      model: env.AZURE_OPENAI_DEPLOYMENT,
    }, system, prompt, images);
  }
  return callOpenAIText({
    label: 'openai',
    url: 'https://api.openai.com/v1/responses',
    headers: { authorization: `Bearer ${env.OPENAI_API_KEY}` },
    model: env.OPENAI_MODEL || 'gpt-4o',
  }, system, prompt, images);
}

// OpenAI / Azure OpenAI Responses API, plain text (no tools). With attachments
// the input becomes one user message of parts, which is the only shape the
// Responses API takes an image in.
async function callOpenAIText(cfg, system, user, images = []) {
  const input = images.length
    ? [{
      role: 'user',
      content: [
        { type: 'input_text', text: user },
        ...images.map((img) => ({
          type: 'input_image',
          image_url: `data:${img.mime};base64,${img.data}`,
        })),
      ],
    }]
    : user;
  const res = await fetch(cfg.url, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...cfg.headers },
    body: JSON.stringify({
      model: cfg.model,
      instructions: system,
      input,
      max_output_tokens: 16000,
    }),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => '');
    throw new Error(`${cfg.label} ${res.status}: ${detail.slice(0, 300)}`);
  }
  const data = await res.json();
  if (typeof data.output_text === 'string' && data.output_text) return data.output_text;
  let text = '';
  for (const item of data.output || []) {
    if (item.type !== 'message') continue;
    for (const c of item.content || []) {
      if (c.type === 'output_text') text += c.text || '';
    }
  }
  if (!text) throw new Error(`${cfg.label}: empty output`);
  return text;
}

// fal-ai/any-llm: text in, text out. No tools, no streaming needed here.
async function callFal(env, systemPrompt, prompt) {
  const res = await fetch(FAL_URL, {
    method: 'POST',
    headers: { authorization: `Key ${env.FAL_KEY}`, 'content-type': 'application/json' },
    body: JSON.stringify({
      model: env.FAL_MODEL || DEFAULT_FAL_MODEL,
      system_prompt: systemPrompt,
      prompt,
    }),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => '');
    throw new Error(`fal ${res.status}: ${detail.slice(0, 300)}`);
  }
  const data = await res.json();
  if (data && data.error) throw new Error(`fal: ${String(data.error).slice(0, 200)}`);
  const text = typeof data.output === 'string' ? data.output
    : (typeof data.response === 'string' ? data.response : '');
  if (!text) throw new Error('empty fal output');
  return text;
}

function extractJson(text) {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start < 0 || end <= start) throw new Error('no JSON in model output');
  return JSON.parse(text.slice(start, end + 1));
}

// Minimal RSS reader — Workers have no DOM parser, and Google News RSS is a
// stable, well-formed shape, so a couple of regexes are enough.
const RSS_ITEM = /<item\b[^>]*>([\s\S]*?)<\/item>/g;
function rssField(block, tag) {
  const m = block.match(new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`, 'i'));
  if (!m) return '';
  const cdata = m[1].match(/<!\[CDATA\[([\s\S]*?)\]\]>/);
  return (cdata ? cdata[1] : m[1]).trim();
}
function decodeEntities(s) {
  return s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'").replace(/&apos;/g, "'").replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&');
}
function stripTags(s) { return decodeEntities(s.replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim(); }

function parseNewsRss(xml) {
  const items = [];
  let m;
  while ((m = RSS_ITEM.exec(xml))) {
    const block = m[1];
    const rawTitle = decodeEntities(rssField(block, 'title'));
    const url = decodeEntities(rssField(block, 'link'));
    const published = rssField(block, 'pubDate');
    let source = decodeEntities(rssField(block, 'source'));
    let title = rawTitle;
    // Google News titles read "Headline - Source"; split when there's no
    // <source> element to lean on.
    if (!source) {
      const idx = rawTitle.lastIndexOf(' - ');
      if (idx > 0) { title = rawTitle.slice(0, idx); source = rawTitle.slice(idx + 3); }
    }
    const snippet = stripTags(rssField(block, 'description')).slice(0, 300);
    if (title) {
      items.push({
        title: title.slice(0, 300),
        source: source.slice(0, 120),
        url: url.slice(0, 1000),
        published: published.slice(0, 60),
        snippet,
      });
    }
  }
  return items;
}

// One Google News RSS query. From datacenter IPs Google sometimes serves a
// cookie-consent interstitial (no <item>s) instead of the feed; the CONSENT
// cookie + a browser UA skips it. Retry once to smooth over that and transient
// blips across Cloudflare colos.
const GNEWS_LOCALE = 'hl=zh-CN&gl=CN&ceid=CN:zh-Hans';

// Cloudflare fetch has no default timeout, so a hung Google response would
// otherwise block the whole request — abort each attempt after 7s.
async function fetchRssItems(url) {
  for (let attempt = 0; attempt < 2; attempt++) {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 7000);
    try {
      const res = await fetch(url, {
        signal: ctrl.signal,
        headers: {
          'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36',
          cookie: 'CONSENT=YES+cb.20210328-17-p0.en+FX+000',
          'accept-language': 'zh-CN,zh;q=0.9',
        },
      });
      if (res.ok) {
        const items = parseNewsRss(await res.text());
        if (items.length) return items;
      }
    } catch {
      // timeout or network error — retry once
    } finally {
      clearTimeout(timer);
    }
  }
  return [];
}

const fetchNewsQuery = (query) =>
  fetchRssItems(`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&${GNEWS_LOCALE}`);

// Current top headlines, no query. First safety net when topical search comes
// back empty (Google sometimes serves a consent/empty page to datacenter IPs).
const fetchTopStories = () => fetchRssItems(`https://news.google.com/rss?${GNEWS_LOCALE}`);

// Final safety net: major Simplified-Chinese news RSS feeds that (unlike Google
// News) serve datacenter IPs reliably. Used only when Google News is blocked at
// the current Cloudflare colo, so a digest can still be produced.
const RELIABLE_FEEDS = [
  'https://feeds.bbci.co.uk/zhongwen/simp/rss.xml',
  'https://rss.dw.com/rdf/rss-chi-all',
];

async function gatherNews(queries) {
  const seen = new Set();
  const out = [];
  const take = (items) => {
    for (const item of items.slice(0, NEWS_PER_QUERY)) {
      if (!item.title || seen.has(item.title)) continue;
      seen.add(item.title);
      out.push(item);
      if (out.length >= MAX_NEWS_ITEMS) break;
    }
  };
  // Fetch all query feeds concurrently — bounded by the slowest single fetch,
  // not the sum — then merge in query order.
  const perQuery = await Promise.all(queries.slice(0, MAX_QUERIES).map(fetchNewsQuery));
  for (const items of perQuery) take(items);
  // Topical search found nothing — fall back to Google top stories, then to
  // major Chinese feeds if Google is blocked at this colo.
  if (out.length === 0) take(await fetchTopStories());
  if (out.length === 0) {
    const feeds = await Promise.all(RELIABLE_FEEDS.map(fetchRssItems));
    for (const items of feeds) take(items);
  }
  return out;
}

const clampHsk = (n) => Math.max(1, Math.min(6, Math.round(n)));

// Best-effort numeric HSK from the planner: prefer its `hsk` field, else pull
// the first 1-6 digit out of the prose estimate, else default to a gentle 2.
function estimateHsk(plan) {
  if (Number.isFinite(plan.hsk)) return clampHsk(plan.hsk);
  const m = String(plan.level || '').match(/HSK\s*([1-6])/i);
  return m ? Number(m[1]) : 2;
}

// Grounding is the Worker's job for every provider: plan queries -> fetch real
// current headlines from Google News -> the model synthesizes the passage from
// them. Sources are always the real articles used, never model-authored URLs.
// `difficulty` shifts the target band down/up from the learner's estimate so
// they can tune it (news vocabulary runs hard, so the default sits AT level).
async function fetchNews(profile, env, difficulty = 'normal') {
  // 1. Plan the search + estimate the level from the learner's vocabulary.
  const plan = extractJson(await callModel(env, TOPICS_SYSTEM, `Learner profile:\n${JSON.stringify(profile)}`));
  const level = typeof plan.level === 'string' ? plan.level : '';
  const topics = (Array.isArray(plan.topics) ? plan.topics : [])
    .filter((t) => typeof t === 'string').slice(0, MAX_TOPICS);
  const queries = (Array.isArray(plan.queries) ? plan.queries : [])
    .filter((t) => typeof t === 'string' && t.trim()).slice(0, MAX_QUERIES);
  if (queries.length === 0) throw new Error('model produced no search queries');

  const estimated = estimateHsk(plan);
  const delta = difficulty === 'easier' ? -1 : difficulty === 'harder' ? 1 : 0;
  const target = clampHsk(estimated + delta);

  // 2. Fetch real, current headlines (keyless Google News RSS).
  const items = await gatherNews(queries);
  if (items.length === 0) throw new Error('no current news found for these topics');

  // 3. Synthesize the passage from those headlines, at the target band.
  const headlines = items
    .map((it, i) => `${i + 1}. [${it.source || 'news'}${it.published ? ', ' + it.published : ''}] ${it.title}${it.snippet ? ' — ' + it.snippet : ''}`)
    .join('\n');
  const list = (xs) => (Array.isArray(xs) && xs.length ? xs.join('、') : '(none yet)');
  const vocabBlock = `The learner's vocabulary (build the passage from these):\n`
    // Listed first and called out hardest: these are the cards in the review
    // queue this week. Meeting one in a real sentence is the whole point.
    + `- IN THEIR REVIEW QUEUE RIGHT NOW (use as many as read naturally — highest priority): ${list(profile.studyingWords)}\n`
    + `- Known words (reuse liberally): ${list(profile.knownWords)}\n`
    + `- Recently saved (weave in naturally): ${list(profile.recentWords)}\n`
    + `- Struggling with (include a few in clear, simple contexts): ${list(profile.strugglingWords)}`;
  const prompt = `TARGET HSK band: ${target} (write for a HSK ${target} reader; difficulty preference: ${difficulty}).\n`
    + `Learner's estimated level: ${level || `HSK ${estimated}`}\n\n`
    + `${vocabBlock}\n\nTopics: ${topics.join(', ') || 'general'}\n\nCurrent news items:\n${headlines}`;
  const digest = sanitizeNews({
    ...extractJson(await callModel(env, NEWS_SYNTH_SYSTEM, prompt)),
    level: level || `HSK ${estimated}`,
    topics,
    sources: items.map((it) => ({ title: it.title, url: it.url })),
  });
  digest.targetHsk = target;
  digest.difficulty = difficulty;
  if (!digest.article) throw new Error('model returned no article');
  return digest;
}

// Clamp the model's output to the shape the extension renders; anything
// missing or oversized becomes an empty/truncated value rather than an error.
function sanitizeNews(parsed) {
  const str = (v, max) => (typeof v === 'string' ? v.slice(0, max) : '');
  const topics = (Array.isArray(parsed.topics) ? parsed.topics : [])
    .filter((t) => typeof t === 'string').slice(0, 12).map((t) => t.slice(0, 80));
  const glossary = (Array.isArray(parsed.glossary) ? parsed.glossary : [])
    .filter((g) => g && typeof g === 'object').slice(0, 40)
    .map((g) => ({ word: str(g.word, 60), pinyin: str(g.pinyin, 120), meaning: str(g.meaning, 300) }))
    .filter((g) => g.word);
  const sources = (Array.isArray(parsed.sources) ? parsed.sources : [])
    .filter((s) => s && typeof s === 'object' && /^https?:\/\//.test(s.url || '')).slice(0, MAX_SOURCES)
    .map((s) => ({ title: str(s.title, 300), url: str(s.url, 1000) }));
  return {
    level: str(parsed.level, 300),
    topics,
    title: str(parsed.title, 300),
    titlePinyin: str(parsed.titlePinyin, 600),
    article: str(parsed.article, MAX_ARTICLE_CHARS),
    englishSummary: str(parsed.englishSummary, 2000),
    glossary,
    sources,
  };
}

async function handleNews(request, env) {
  const token = bearerToken(request);
  if (!token) return json({ error: 'missing or malformed bearer token' }, 401);
  const model = resolveModel(request, env, 'The news digest');
  if (model.error) return model.error;

  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: 'invalid JSON' }, 400);
  }
  const profile = body.profile;
  if (!profile || typeof profile !== 'object' || Array.isArray(profile)) {
    return json({ error: 'missing profile' }, 400);
  }
  const difficulty = ['easier', 'normal', 'harder'].includes(body.difficulty) ? body.difficulty : 'normal';
  const profileJson = JSON.stringify(profile);
  if (profileJson.length > MAX_PROFILE_BYTES) return json({ error: 'profile too large' }, 413);

  const now = Date.now();
  const db = env.DB;
  const ip = request.headers.get('cf-connecting-ip') || 'unknown';
  const user = await getUser(db, await sha256Hex(token), ip, now);
  if (!user) return json({ error: 'too many new pairings from this address; try later' }, 429);

  const cached = await db
    .prepare('SELECT doc, created_at FROM news WHERE user_id = ?')
    .bind(user.id)
    .first();
  const cachedDoc = cached ? JSON.parse(cached.doc) : null;
  const age = cached ? now - cached.created_at : Infinity;
  const sameDifficulty = cachedDoc && (cachedDoc.difficulty || 'normal') === difficulty;
  // Normal (non-forced) loads show the last digest within the TTL — never spend
  // on a tab open. A forced refresh regenerates, except within the short
  // anti-spam floor when the difficulty is unchanged (so changing difficulty
  // always re-generates right away).
  if (cachedDoc && ((!body.force && age < NEWS_TTL_MS) || (age < NEWS_MIN_INTERVAL_MS && sameDifficulty))) {
    return json({ ...cachedDoc, generatedAt: cached.created_at, cached: true });
  }

  let digest;
  try {
    digest = await fetchNews(profile, model.env, difficulty);
  } catch (err) {
    console.log(JSON.stringify({ event: 'news_error', error: String(err && err.message || err) }));
    if (cachedDoc) {
      return json({ ...cachedDoc, generatedAt: cached.created_at, cached: true, stale: true });
    }
    return json({ error: 'could not generate your news digest; try again later', detail: String(err && err.message || err).slice(0, 300) }, 502);
  }

  await db
    .prepare(
      `INSERT INTO news (user_id, doc, profile_hash, created_at) VALUES (?, ?, ?, ?)
       ON CONFLICT(user_id) DO UPDATE SET
         doc = excluded.doc, profile_hash = excluded.profile_hash, created_at = excluded.created_at`,
    )
    .bind(user.id, JSON.stringify(digest), await sha256Hex(profileJson), now)
    .run();
  return json({ ...digest, generatedAt: now, cached: false });
}

// ---------------------------------------------------------------------------
// Study-guide tutor: answer one question about the guide the learner is
// reading, anchored to whatever they highlighted.
// ---------------------------------------------------------------------------

const ASK_SYSTEM = `You are a precise, patient Mandarin Chinese tutor sitting beside a learner. They might be reading a study guide, reviewing a flashcard, reading a news passage, or looking over their saved words — the message says which. Answer the single question they ask.

Rules:
- Answer in English. Write Chinese in Simplified, and give pinyin in parentheses the first time a word appears.
- If the learner highlighted something, that highlight is what they are pointing at. Answer about THAT specific text, and quote the relevant few characters back so it is clear what you are explaining.
- On a flashcard, the most useful answer is usually about USAGE: when a native speaker would reach for this word, what it collocates with, and how it differs from the near synonym the learner probably already knows. Do not just restate the dictionary gloss they can already see.
- Be short and concrete: two to six sentences, or a few short lines. No preamble, no "great question", no summary of what you are about to say.
- For a grammar question: name the pattern, give ONE minimal example sentence, and state the single mistake learners most often make with it.
- For a vocabulary question: give the meaning, the register (spoken/written/formal), and a near-synonym contrast if one matters.
- Stay at or near the learner's level. Do not introduce advanced vocabulary to explain a beginner point.
- If the learner attached an image — a sign, a menu, a screenshot, a page of a book — read the Chinese in it and answer about that. Transcribe the characters you are talking about so they can be looked up, and say plainly if part of it is too blurry or cropped to read rather than guessing at it.
- Never invent a word, a character, or a usage. If you are not sure, say you are not sure.
- Plain text only. No markdown, no asterisks, no headings, no numbered lists with special formatting — just sentences and, at most, short lines separated by newlines.`;

// One CREATE per isolate rather than a schema migration the user has to run:
// a model-backed endpoint should work on a Worker deployed before it existed.
// `kind` keeps each endpoint's budget separate, so saving a run of sentences
// cannot spend the tutor's allowance.
let usageTableReady = false;
async function ensureUsageLog(db) {
  if (usageTableReady) return;
  await db.batch([
    db.prepare(`CREATE TABLE IF NOT EXISTS usage_log (
      user_id INTEGER NOT NULL, kind TEXT NOT NULL, created_at INTEGER NOT NULL)`),
    db.prepare('CREATE INDEX IF NOT EXISTS usage_log_user ON usage_log(user_id, kind, created_at)'),
  ]);
  usageTableReady = true;
}

// How many calls of this kind the user has made in the last hour.
async function usageLastHour(db, userId, kind, now) {
  const { recent } = await db
    .prepare('SELECT COUNT(*) AS recent FROM usage_log WHERE user_id = ? AND kind = ? AND created_at > ?')
    .bind(userId, kind, now - 60 * 60 * 1000)
    .first();
  return recent;
}

function recordUsage(db, userId, kind, now) {
  return db.prepare('INSERT INTO usage_log (user_id, kind, created_at) VALUES (?, ?, ?)')
    .bind(userId, kind, now).run();
}

function askText(value, max) {
  return typeof value === 'string' ? value.slice(0, max).trim() : '';
}

// Images the learner attached to the question — a photo of a menu, a sign, a
// screenshot of a sentence they hit somewhere else. The client shrinks them
// before sending (a pasted screenshot is easily 4MB), so these caps are a
// backstop against a caller that does not, not the working size.
const ASK_IMAGE_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp', 'image/gif']);
const MAX_ASK_IMAGES = 3;
const MAX_IMAGE_BASE64 = 1_600_000; // ~1.2MB of pixels each

// Returns { images } or { error } — a bad attachment is worth saying out loud
// rather than dropping silently, since the learner can see they attached it.
function askImages(body) {
  const raw = Array.isArray(body.images) ? body.images : [];
  if (!raw.length) return { images: [] };
  if (raw.length > MAX_ASK_IMAGES) {
    return { error: json({ error: `at most ${MAX_ASK_IMAGES} images per question` }, 400) };
  }
  const images = [];
  for (const item of raw) {
    const mime = item && typeof item.mime === 'string' ? item.mime.toLowerCase() : '';
    const data = item && typeof item.data === 'string' ? item.data : '';
    if (!ASK_IMAGE_TYPES.has(mime)) {
      return { error: json({ error: `unsupported image type "${mime.slice(0, 40)}"` }, 400) };
    }
    if (!data || !/^[A-Za-z0-9+/=]+$/.test(data)) {
      return { error: json({ error: 'image data must be base64' }, 400) };
    }
    if (data.length > MAX_IMAGE_BASE64) return { error: json({ error: 'image too large' }, 413) };
    images.push({ mime, data });
  }
  return { images };
}

// The guide the learner is on, the part they highlighted, and the last few
// turns — enough for follow-ups like "and the second one?" without shipping
// the whole conversation every time.
function buildAskPrompt(body) {
  const context = body.context && typeof body.context === 'object' ? body.context : {};
  const parts = [];
  const level = Number(context.level);
  if (Number.isInteger(level) && level >= 1 && level <= 9) {
    parts.push(`The learner is reading the HSK ${level} study guide.`);
  } else {
    // Every other surface describes itself: a flashcard, a news passage, the
    // saved library. Without this the model assumes it is a study guide.
    const where = askText(context.where, 200);
    if (where) parts.push(`The learner is looking at ${where}.`);
  }
  const section = askText(context.section, 200);
  if (section) parts.push(`They are in the "${section}" section.`);
  const surrounding = askText(context.text, MAX_CONTEXT_CHARS);
  if (surrounding) parts.push(`Text on screen:\n"""\n${surrounding}\n"""`);
  const selection = askText(body.selection, MAX_SELECTION_CHARS);
  if (selection) {
    parts.push(`THE LEARNER HIGHLIGHTED THIS AND IS ASKING ABOUT IT:\n"""\n${selection}\n"""`);
  }
  const history = (Array.isArray(body.history) ? body.history : [])
    .slice(-MAX_HISTORY_TURNS)
    .filter((m) => m && (m.role === 'user' || m.role === 'assistant') && typeof m.content === 'string')
    .map((m) => `${m.role === 'user' ? 'Learner' : 'You'}: ${m.content.slice(0, MAX_HISTORY_CHARS)}`);
  if (history.length) parts.push(`Earlier in this conversation:\n${history.join('\n')}`);
  const attachedCount = Array.isArray(body.images) ? body.images.length : 0;
  if (attachedCount) {
    parts.push(attachedCount === 1
      ? 'The learner attached an image with this question; it follows.'
      : `The learner attached ${attachedCount} images with this question; they follow.`);
  }
  parts.push(`Question: ${askText(body.question, MAX_QUESTION_CHARS)}`);
  return parts.join('\n\n');
}

async function handleAsk(request, env) {
  const token = bearerToken(request);
  if (!token) return json({ error: 'missing or malformed bearer token' }, 401);
  const model = resolveModel(request, env, 'The study-guide tutor');
  if (model.error) return model.error;

  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: 'invalid JSON' }, 400);
  }
  const question = askText(body.question, MAX_QUESTION_CHARS);
  if (!question) return json({ error: 'missing question' }, 400);
  const attached = askImages(body);
  if (attached.error) return attached.error;

  const now = Date.now();
  const db = env.DB;
  const ip = request.headers.get('cf-connecting-ip') || 'unknown';
  const user = await getUser(db, await sha256Hex(token), ip, now);
  if (!user) return json({ error: 'too many new pairings from this address; try later' }, 429);

  await ensureUsageLog(db);
  const recent = await usageLastHour(db, user.id, 'ask', now);
  if (recent >= ASK_PER_HOUR) {
    return json({ error: `question limit reached (${ASK_PER_HOUR} per hour); try again later` }, 429);
  }

  let answer;
  try {
    answer = await callModel(model.env, ASK_SYSTEM, buildAskPrompt(body), attached.images);
  } catch (err) {
    console.log(JSON.stringify({ event: 'ask_error', error: String(err && err.message || err) }));
    return json({
      error: 'could not answer that right now; try again shortly',
      detail: String(err && err.message || err).slice(0, 300),
    }, 502);
  }

  await recordUsage(db, user.id, 'ask', now);
  return json({ answer: String(answer).slice(0, MAX_ANSWER_CHARS).trim(), generatedAt: now });
}

// ---------------------------------------------------------------------------
// Translating one card's worth of Chinese.
// ---------------------------------------------------------------------------

const TRANSLATE_SYSTEM = `You translate one short piece of Mandarin Chinese into English for the back of a learner's flashcard.

Rules:
- Give the natural English a fluent speaker would actually use, not a word-by-word rendering. The learner can already see every word's dictionary entry; what they lack is what the whole thing MEANS.
- Keep it to one sentence wherever the Chinese is one sentence. No preamble, no "This sentence means".
- Preserve register: casual Chinese gets casual English, formal gets formal.
- If the Chinese is a fragment rather than a full sentence, translate the fragment as a fragment.
- If a word order or structure would surprise an English speaker, add a SHORT literal rendering as well. Otherwise leave it empty.
- If the input is not Chinese, or is too garbled to translate, return an empty translation.

Respond with ONLY a JSON object (no markdown fences):
{ "translation": "natural English", "literal": "word-order-preserving rendering, or empty" }`;

// POST /api/translate { text } -> { translation, literal }
async function handleTranslate(request, env) {
  const token = bearerToken(request);
  if (!token) return json({ error: 'missing or malformed bearer token' }, 401);
  const model = resolveModel(request, env, 'Translation');
  if (model.error) return model.error;

  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: 'invalid JSON' }, 400);
  }
  const text = String(body.text || '').replace(/\s+/g, ' ').trim();
  if (!text) return json({ error: 'missing text' }, 400);
  if (text.length > MAX_TRANSLATE_CHARS) return json({ error: 'text too long' }, 413);
  if (!/[\u3400-\u9fff\uf900-\ufaff]/.test(text)) {
    return json({ error: 'not Chinese text' }, 400);
  }

  const now = Date.now();
  const db = env.DB;
  const ip = request.headers.get('cf-connecting-ip') || 'unknown';
  const user = await getUser(db, await sha256Hex(token), ip, now);
  if (!user) return json({ error: 'too many new pairings from this address; try later' }, 429);

  await ensureUsageLog(db);
  if (await usageLastHour(db, user.id, 'translate', now) >= TRANSLATE_PER_HOUR) {
    return json({ error: `translation limit reached (${TRANSLATE_PER_HOUR} per hour); try again later` }, 429);
  }

  let parsed;
  try {
    parsed = extractJson(await callModel(model.env, TRANSLATE_SYSTEM, text));
  } catch (err) {
    console.log(JSON.stringify({ event: 'translate_error', error: String(err && err.message || err) }));
    return json({
      error: 'could not translate that right now; try again shortly',
      detail: String(err && err.message || err).slice(0, 300),
    }, 502);
  }

  const clean = (v) => String(v == null ? '' : v).replace(/\s+/g, ' ').trim().slice(0, MAX_TRANSLATION_CHARS);
  const translation = clean(parsed.translation);
  // An empty translation is the model's way of saying the input was not
  // translatable. Say so rather than writing an empty card back.
  if (!translation) return json({ error: 'nothing translatable in that text' }, 422);

  await recordUsage(db, user.id, 'translate', now);
  return json({ translation, literal: clean(parsed.literal), generatedAt: now });
}

// ---------------------------------------------------------------------------
// The placement interview
// ---------------------------------------------------------------------------

const PLACEMENT_SYSTEM = `You are a Mandarin examiner running a spoken-style placement interview in text. The learner types their replies. You conduct the interview one turn at a time: you mark the reply they just gave, then set the next task.

The interview is adaptive, and the client owns the ladder. It tells you which HSK levels this turn may be aimed at — usually a suggested level and the one either side of it — and gives you the published descriptors for each. You may pick any level from that list and no other. Pick it AFTER marking the reply below: take the suggested level unless that reply clearly says otherwise, step up if they handled the last task easily, step down if it defeated them. Never go outside the list, even if you think the right level is elsewhere; a level missing from it has already been ruled out or already been asked about enough.

WRITING THE TASK
- Write it in Mandarin, pitched at the level you picked. One task per turn, two or three sentences at most.
- Vary what you ask for across the interview: answer a question about their life, react to a situation, retell something you just said, explain a preference and why, translate one short English sentence, or complete a sentence you start. Do not ask the same kind of thing twice in a row.
- Levels 1-2 may carry a short English gloss in brackets after the Chinese. Level 3 and up must be Chinese only — reading the question is part of the test.
- Lean on words the learner's deck says they know, so a stumble is about the level and not about one unlucky word. Where the deck lists words they keep failing, work one in when it fits naturally.
- Never say what level you are testing, never give a score, never praise or correct mid-interview. Marking is invisible to them until the end. Just react briefly and naturally, then ask the next thing.
- Never answer your own question or model the reply you want.

MARKING THE PREVIOUS ANSWER
- comprehension 0-3: did they understand what was asked? 0 no reply or clearly did not understand, 1 caught the topic only, 2 understood with effort or one misreading, 3 understood fully.
- production 0-3: was the Chinese they wrote accurate and natural for the TARGET LEVEL? 0 no usable Chinese (blank, English only, "I don't know"), 1 isolated words or heavy errors, 2 gets the meaning across with errors below this level's standard, 3 accurate and natural at this level.
- Mark against the target level, not against a native speaker. A perfectly good HSK 2 answer to an HSK 5 task is a low production mark at 5 — that is the measurement working, not harshness.
- Answering in English, in pinyin, or with "I don't know" is real evidence: mark production 0 and say so in the comment. Do not award marks for effort.
- errors: up to three concrete ones. Quote the learner's own words in "span", give the corrected Chinese in "correction", and say what the rule is in one short English clause. Only real errors — do not invent them to look thorough, and do not list stylistic preferences as errors.
- comment: one short English sentence the learner will read afterwards. Specific, not "good job".

THE FINAL TURN
When told this is the final turn, add a "result" object summarizing the whole interview: what they can reliably do, where it came apart, and what to work on. Base it on the transcript in front of you. Do not state an overall HSK level number in any text — the client computes that from your marks, and a second number that disagrees with it is worse than no number.

Respond with ONLY a JSON object (no markdown fences):
{
  "level": 1-9, the level you picked for the task, from the allowed list
  "reply": "what you say next, in Mandarin (plus a bracketed English gloss only at levels 1-2)",
  "taskType": "question | situation | retell | translate | complete | wind-down",
  "assess": null,
  "result": null
}
"assess" is null on the opening turn only; on every other turn it is
{ "comprehension": 0-3, "production": 0-3, "errors": [{ "span": "", "correction": "", "note": "" }], "vocabUsed": [""], "comment": "" }
"result" is null except on the final turn, where it is
{ "summary": "2-3 English sentences", "strengths": [""], "gaps": [""], "advice": [""] }`;

const MAX_PLACEMENT_HISTORY = 26;      // messages of transcript sent back
const MAX_PLACEMENT_MESSAGE = 1200;    // one turn of it
const MAX_PLACEMENT_ANSWER = 2000;     // what the learner just typed
const MAX_PLACEMENT_REPLY = 600;
const MAX_PLACEMENT_ERRORS = 3;
const MAX_PLACEMENT_RUBRIC_BYTES = 8 * 1024;

// The rubrics, the deck, the transcript, and which levels this turn may be
// aimed at. The rubrics travel from the client because the guides — the app's
// copy of the published standard — live in the extension, and rating against
// the same descriptors the learner can go and read is the whole point of
// sending them.
function buildPlacementPrompt(body, allowed) {
  const parts = [];
  const target = Number(body.target);
  const rubrics = (Array.isArray(body.rubrics) ? body.rubrics : [])
    .filter((r) => r && typeof r === 'object' && allowed.includes(Number(r.level)));

  parts.push(allowed.length > 1
    ? `Allowed levels for this turn: ${allowed.join(', ')}. Suggested: HSK ${target}.`
    : `This turn must be aimed at HSK ${target}.`);

  for (const rubric of rubrics) {
    const lines = [];
    if (Array.isArray(rubric.canDo)) {
      lines.push(`At this level a learner can:\n- ${rubric.canDo.slice(0, 8).join('\n- ')}`);
    }
    if (Array.isArray(rubric.grammar)) {
      lines.push(`Grammar introduced at this level:\n- ${rubric.grammar.slice(0, 14).join('\n- ')}`);
    }
    if (Array.isArray(rubric.vocab)) {
      lines.push(`Representative vocabulary: ${rubric.vocab.slice(0, 60).join('、')}`);
    }
    parts.push(`RUBRIC FOR HSK ${Number(rubric.level)}\n${lines.join('\n\n')}`);
  }

  const profile = body.profile && typeof body.profile === 'object' ? body.profile : null;
  if (profile) {
    parts.push('The learner\'s flashcard deck, for pitching the task — not for marking:\n'
      + `${JSON.stringify(profile)}`);
  }

  const history = (Array.isArray(body.history) ? body.history : [])
    .slice(-MAX_PLACEMENT_HISTORY)
    .filter((m) => m && typeof m.content === 'string'
      && (m.role === 'examiner' || m.role === 'learner'))
    .map((m) => `${m.role === 'learner' ? 'Learner' : 'You'}: ${m.content.slice(0, MAX_PLACEMENT_MESSAGE)}`);
  if (history.length) parts.push(`The interview so far:\n${history.join('\n')}`);

  const answer = askText(body.answer, MAX_PLACEMENT_ANSWER);
  if (answer) {
    parts.push(`THE LEARNER'S REPLY TO YOUR LAST TASK — mark this one:\n"""\n${answer}\n"""`);
    parts.push(`Their reply was to a task aimed at HSK ${Number(body.answeredLevel) || target}. Mark it against THAT level.`);
  } else if (history.length) {
    // A turn arriving with an empty answer is a learner who pressed send with
    // nothing in the box, or skipped. That is a mark of zero, not a missing
    // measurement — saying so here stops the model marking the void generously.
    parts.push('The learner sent no reply to your last task. Mark comprehension 0 and production 0.');
  }

  if (body.finish) {
    parts.push('THIS IS THE FINAL TURN. Mark the reply above, then close the interview warmly in '
      + 'one or two sentences and fill in "result". Do not set another task.');
  } else if (!history.length) {
    parts.push('This is the opening turn. There is nothing to mark yet, so "assess" is null. '
      + 'Greet them in one short line and set the first task.');
  }
  return parts.join('\n\n');
}

const clampMark = (value) => Math.min(3, Math.max(0, Math.round(Number(value)) || 0));

// The model is marking, so its numbers are taken as given — but the shapes are
// not. A mark that arrives as "3/3", an errors array of 40 items, or a result
// object on a turn that is not the last one would all end up stored in the
// learner's history and charted, so each is coerced or dropped here.
function cleanAssess(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const errors = (Array.isArray(raw.errors) ? raw.errors : [])
    .slice(0, MAX_PLACEMENT_ERRORS)
    .map((e) => ({
      span: askText(e && e.span, 120),
      correction: askText(e && e.correction, 200),
      note: askText(e && e.note, 200),
    }))
    .filter((e) => e.span || e.correction);
  return {
    comprehension: clampMark(raw.comprehension),
    production: clampMark(raw.production),
    errors,
    vocabUsed: (Array.isArray(raw.vocabUsed) ? raw.vocabUsed : [])
      .slice(0, 12).map((w) => askText(w, 20)).filter(Boolean),
    comment: askText(raw.comment, 300),
  };
}

function cleanResult(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const list = (value) => (Array.isArray(value) ? value : [])
    .slice(0, 5).map((s) => askText(s, 220)).filter(Boolean);
  return {
    summary: askText(raw.summary, 700),
    strengths: list(raw.strengths),
    gaps: list(raw.gaps),
    advice: list(raw.advice),
  };
}

// POST /api/placement -> { reply, taskType, assess, result }
async function handlePlacement(request, env) {
  const token = bearerToken(request);
  if (!token) return json({ error: 'missing or malformed bearer token' }, 401);
  const model = resolveModel(request, env, 'The placement interview');
  if (model.error) return model.error;

  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: 'invalid JSON' }, 400);
  }
  const target = Number(body.target);
  if (!Number.isInteger(target) || target < 1 || target > 9) {
    return json({ error: 'target must be an HSK level, 1 to 9' }, 400);
  }
  // The band the client's ladder will accept back. The suggestion is always in
  // it, so a client that sends no band still gets a working turn.
  const allowed = [...new Set([target, ...(Array.isArray(body.allowed) ? body.allowed : [])]
    .map(Number).filter((n) => Number.isInteger(n) && n >= 1 && n <= 9))].sort();
  if (JSON.stringify(body.rubrics || null).length > MAX_PLACEMENT_RUBRIC_BYTES) {
    return json({ error: 'rubrics too large' }, 413);
  }
  if (JSON.stringify(body.profile || null).length > MAX_PROFILE_BYTES) {
    return json({ error: 'profile too large' }, 413);
  }

  const now = Date.now();
  const db = env.DB;
  const ip = request.headers.get('cf-connecting-ip') || 'unknown';
  const user = await getUser(db, await sha256Hex(token), ip, now);
  if (!user) return json({ error: 'too many new pairings from this address; try later' }, 429);

  await ensureUsageLog(db);
  if (await usageLastHour(db, user.id, 'placement', now) >= PLACEMENT_PER_HOUR) {
    return json({
      error: `placement limit reached (${PLACEMENT_PER_HOUR} questions per hour); try again later`,
    }, 429);
  }

  let parsed;
  try {
    parsed = extractJson(await callModel(
      model.env, PLACEMENT_SYSTEM, buildPlacementPrompt(body, allowed)));
  } catch (err) {
    console.log(JSON.stringify({ event: 'placement_error', error: String(err && err.message || err) }));
    return json({
      error: 'could not continue the interview right now; try again shortly',
      detail: String(err && err.message || err).slice(0, 300),
    }, 502);
  }

  const reply = askText(parsed.reply, MAX_PLACEMENT_REPLY);
  if (!reply) return json({ error: 'the examiner returned nothing to say' }, 502);

  await recordUsage(db, user.id, 'placement', now);
  return json({
    // A level outside the band is not a suggestion to weigh — the ladder
    // already ruled it out — so it becomes the suggestion the client sent.
    level: allowed.includes(Number(parsed.level)) ? Number(parsed.level) : target,
    reply,
    taskType: askText(parsed.taskType, 40),
    // Nothing to mark on the opening turn, and a result only on the last one:
    // whatever the model returned otherwise is dropped rather than charted.
    assess: body.answer || (Array.isArray(body.history) && body.history.length)
      ? cleanAssess(parsed.assess) : null,
    result: body.finish ? cleanResult(parsed.result) : null,
    generatedAt: now,
  });
}

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }
    const { pathname } = new URL(request.url);
    if (pathname === '/api/health') return json({ ok: true });
    if (pathname === '/api/sync') {
      if (request.method !== 'POST') return json({ error: 'POST only' }, 405);
      try {
        return await handleSync(request, env);
      } catch (err) {
        console.log(JSON.stringify({ event: 'sync_error', error: String(err && err.stack || err) }));
        return json({ error: 'internal error' }, 500);
      }
    }
    if (pathname === '/api/news') {
      if (request.method !== 'POST') return json({ error: 'POST only' }, 405);
      try {
        return await handleNews(request, env);
      } catch (err) {
        console.log(JSON.stringify({ event: 'news_error', error: String(err && err.stack || err) }));
        return json({ error: 'internal error' }, 500);
      }
    }
    if (pathname === '/api/ask') {
      if (request.method !== 'POST') return json({ error: 'POST only' }, 405);
      try {
        return await handleAsk(request, env);
      } catch (err) {
        console.log(JSON.stringify({ event: 'ask_error', error: String(err && err.stack || err) }));
        return json({ error: 'internal error' }, 500);
      }
    }
    if (pathname === '/api/placement') {
      if (request.method !== 'POST') return json({ error: 'POST only' }, 405);
      try {
        return await handlePlacement(request, env);
      } catch (err) {
        console.log(JSON.stringify({ event: 'placement_error', error: String(err && err.stack || err) }));
        return json({ error: 'internal error' }, 500);
      }
    }
    if (pathname === '/api/translate') {
      if (request.method !== 'POST') return json({ error: 'POST only' }, 405);
      try {
        return await handleTranslate(request, env);
      } catch (err) {
        console.log(JSON.stringify({ event: 'translate_error', error: String(err && err.stack || err) }));
        return json({ error: 'internal error' }, 500);
      }
    }
    // Non-/api paths are served by the static asset handler and never reach
    // the Worker (run_worker_first is scoped to /api/*).
    return json({ error: 'not found' }, 404);
  },

  // Daily cron: drop tombstones old enough that every device has seen them,
  // and rate-limit rows that are past the window they guard.
  async scheduled(_event, env) {
    const now = Date.now();
    await env.DB
      .prepare('DELETE FROM cards WHERE deleted = 1 AND deleted_at < ?')
      .bind(now - TOMBSTONE_TTL_MS)
      .run();
    await env.DB
      .prepare('DELETE FROM usage_log WHERE created_at < ?')
      .bind(now - USAGE_LOG_TTL_MS)
      .run()
      .catch(() => {}); // the table only exists once a model endpoint has run
  },
};
